# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

sudo: required
services:
  - docker
before_install:
  - "./tools/travis/setup.sh"
install: true
script:
  - "./tools/travis/scan.sh && ./tools/travis/build.sh && ./tools/travis/test.sh"

deploy:
  - provider: script
    skip_cleanup: true
    script: "./tools/travis/publish.sh openwhisk ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
    on:
      tags: true
      all_branches: true
      repo: apache/incubator-openwhisk-runtime-rust
  - provider: script
    skip_cleanup: true
    script: "./tools/travis/publish.sh openwhisk rust1.32 latest"
    on:
      branch: master
      repo: apache/incubator-openwhisk-runtime-rust
