[package]
name = "action_loop"
version = "0.1.0"
authors = ["Roberto Diaz <roberto@theagilemonkeys.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
libc = "0.2.49"
actions = { path = "../actions" }
